import {Dimensions, StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex:1,
        flexDirection:"row",
        flexWrap: 'wrap-reverse',
        alignSelf:'flex-start',
        backgroundColor: 'white',
    },
    containerTop: {
        flex:1,
        flexWrap: 'wrap',
        alignSelf:'flex-end',
        backgroundColor: 'white',
        marginTop: '50%',
    },
    texto: {
        fontSize: 70,
        fontFamily: 'Roboto',
        color: '#38acd6',
    },
    textoS: {
        fontSize: 70,
        fontFamily: 'Roboto',
        color: 'white',
    },
    texto_AC: {
        fontSize: 50,
        fontFamily: 'Roboto',
        color: 'white',
    },
    botao: {
        margin:5,
        width: Dimensions.get('window').width/5 + 10,
        height: Dimensions.get('window').width/4,
        alignItems:'center',
        justifyContent: 'center',
        backgroundColor:'white',
        borderColor: '#38acd6',
        borderWidth: 3,
        borderRadius: Dimensions.get('window').width/20,
    },
    secondary: {
        margin:5,
        width: Dimensions.get('window').width/5 + 10,
        height: Dimensions.get('window').width/4,
        alignItems:'center',
        justifyContent: 'center',
        backgroundColor:'#FA8E76',
        borderColor: '#FA8E76',
        borderWidth: 3,
        borderRadius: Dimensions.get('window').width/20,
    },
    ternary: {
        margin:5,
        width: Dimensions.get('window').width/5 + 10,
        height: Dimensions.get('window').width/4,
        alignItems:'center',
        justifyContent: 'center',
        backgroundColor:'#7A84A9',
        borderColor: '#7A84A9',
        borderWidth: 3,
        borderRadius: Dimensions.get('window').width/20,
    },
    botao_0: {
        margin:5,
        paddingLeft:24,
        width: Dimensions.get('window').width/5 *2 +30,
        height: Dimensions.get('window').width/4,
        alignItems:'flex-start',
        justifyContent: 'center',
        backgroundColor:'white',
        borderColor: '#38acd6',
        borderWidth: 3,
        borderRadius: Dimensions.get('window').width/20,
    }
});